# Generated by Django 5.0.4 on 2024-04-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
