# Generated by Django 5.0.4 on 2024-05-09 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_promocode_expiration_date_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 8, 18, 19, 24, 695252)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
