# Generated by Django 5.0.4 on 2024-04-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_pickuppoint_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='country',
        ),
    ]
