# Generated by Django 5.0.4 on 2024-05-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_sale_customer_alter_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='category description', max_length=200),
        ),
    ]
