# Generated by Django 5.0.4 on 2024-05-10 16:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_profile_birth_date_alter_promocode_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not definded', max_length=100)),
                ('text', models.TextField(default='not definded')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='not definded', max_length=100)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(default='not definded', null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='duties',
        ),
        migrations.AddField(
            model_name='profile',
            name='job_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='non_secretive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_employee.png', upload_to='images/employees/'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='not definded'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(default='not definded', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(default='not definded'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(default='not definded'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title',
            field=models.CharField(default='not definded', max_length=100),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 9, 19, 34, 17, 897145)),
        ),
        migrations.CreateModel(
            name='AboutArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.article')),
                ('photo', models.ImageField(default='default_image.png', upload_to='images/about_articles/')),
            ],
            bases=('mainapp.article',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.article')),
                ('question', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default_image.png', upload_to='images/faq/')),
            ],
            bases=('mainapp.article',),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.article')),
                ('photo', models.ImageField(default='default_image.png', upload_to='images/news_articles/')),
            ],
            bases=('mainapp.article',),
        ),
    ]
