# Generated by Django 5.0.4 on 2024-05-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_sale_customer_remove_sale_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pick_up_point',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ManyToManyField(related_name='pickup_point', to='mainapp.pickuppoint'),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_points',
            field=models.ManyToManyField(related_name='pickup_points', to='mainapp.pickuppoint'),
        ),
    ]
