# Generated by Django 5.0.4 on 2024-05-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_order_pick_up_point_order_pickup_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_point',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.pickuppoint'),
        ),
    ]
