# Generated by Django 5.0.4 on 2024-09-16 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_product_image_alter_promocode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 16, 14, 25, 42, 888378)),
        ),
    ]
