# Generated by Django 5.0.4 on 2024-09-16 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_alter_promocode_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/employees/default_employee.png', upload_to='images/employees/'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 16, 18, 40, 34, 574908)),
        ),
    ]
