# Generated by Django 5.0.4 on 2024-09-16 16:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_profile_photo_alter_promocode_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='cart', to='mainapp.order'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 16, 19, 57, 0, 759856)),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
