# Generated by Django 5.0.4 on 2024-09-16 17:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_remove_cart_products_remove_cart_user_cart_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 16, 20, 32, 25, 36922)),
        ),
    ]
