# Generated by Django 5.0.4 on 2024-09-16 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_alter_cart_user_alter_promocode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 16, 21, 10, 22, 922762)),
        ),
    ]
