# Generated by Django 5.1.1 on 2024-09-16 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_alter_promocode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pickup_points',
            field=models.ManyToManyField(related_name='products', to='mainapp.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 17, 1, 20, 1, 652771)),
        ),
    ]
