# Generated by Django 5.1.1 on 2024-09-17 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_alter_product_pickup_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pickup_points',
            field=models.ManyToManyField(related_name='pickup_points', to='mainapp.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 17, 19, 52, 19, 909065)),
        ),
    ]
