# Generated by Django 5.1.1 on 2024-09-17 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_alter_promocode_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='image',
            field=models.ImageField(default='images/promocodes/default.png', upload_to='images/promocodes/'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(default='images/vacancies/default.png', upload_to='images/vacancies/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_points',
            field=models.ManyToManyField(related_name='products', to='mainapp.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 18, 2, 17, 37, 679186)),
        ),
    ]
