# Generated by Django 5.0.4 on 2024-09-18 11:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_promocode_image_vacancy_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='image',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='max_usage',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='used_count',
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.promocode'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 18, 14, 25, 36, 638632)),
        ),
    ]
