# Generated by Django 5.0.4 on 2024-09-18 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_alter_order_promocode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 18, 15, 26, 49, 546194)),
        ),
    ]
